import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Header from '../lib/components/Header'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={`pagewidth ${styles.main}`}>

        <div className={styles.gridHalves}>
          <div>
            <h2 className={styles.h2}>Blockchain & Web3</h2>
            <p className={styles.p}>We develop smart contracts and web3 experiences for masses to consume. ERC20 Tokenization, ERC721 Non Fungible Tokenization, decentralized and responsive modern web experiences.</p>
            <p className={styles.p}>Check out our latest projects.</p>
          </div>
          <div>
            <img src="/assets/img/asset-1.svg" />
          </div>


          <div>
            <img src="/assets/img/asset-2.svg" />
          </div>
          <div>
            <p className={`text-uppercase ${styles.p}`}>OUR AIM IS</p>
            <h2 className={styles.h2}>Creating Digital Experiences</h2>
            <p className={styles.p}>We deliver an overall solution including:</p>
            <p className={styles.p}>
              <ul>
                <li>CTO as a Service</li>
                <li>Project Management</li>
                <li>Talent Acquisition</li>
                <li>System Administration / Infra – Dev Ops</li>
                <li>Software Development</li>
                <li>Analytics and Insights</li>
              </ul>
            </p>
          </div>

        </div>

        <div className={`m-y-6`}>
            <p className={`text-uppercase text-center ${styles.p}`}>Our Services</p>
            <h2 className={`text-center ${styles.h2}`}>What We Offer</h2>
        </div>
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}

export default Home
